POST http://localhost:12346/Tokens
Content-Type: application/json

{
    "username": "SSS",
    "password": "Ronnie1996"
}

###
GET http://localhost:12346/Users
###
GET http://localhost:12346/Chats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvbm5pZUEiLCJpYXQiOjE2ODU3NDE5MDR9.Q6MeczrHfbzosvjT_2sPt-Zv8Q51-3ZCcs6Dvqd5eaA
###
POST http://localhost:12346/Chats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNTUyIsImlhdCI6MTY4NjA4NDMzM30.tWZ-ikRKaepX-NgLLv2M_D-CSEo7n2Zda0ntE7YjLiI
Content-Type: application/json

{
    "username": "BBB"
}

###
GET http://localhost:12346/Chats/15/Messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvbm5pZUEiLCJpYXQiOjE2ODU3NDE5MDR9.Q6MeczrHfbzosvjT_2sPt-Zv8Q51-3ZCcs6Dvqd5eaA
###
DELETE http://localhost:12346/Chats/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvbm5pZUEiLCJpYXQiOjE2ODU3NDE5MDR9.Q6MeczrHfbzosvjT_2sPt-Zv8Q51-3ZCcs6Dvqd5eaA


### 
POST http://localhost:12346/Chats/15/Messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvbm5pZUEiLCJpYXQiOjE2ODU3NDE5MDR9.Q6MeczrHfbzosvjT_2sPt-Zv8Q51-3ZCcs6Dvqd5eaA
Content-Type: application/json

{
    "msg": "hellf0000000"
}

###
GET http://localhost:12346/Chats/3/Messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvbm5pZUEiLCJpYXQiOjE2ODU3NDE5MDR9.Q6MeczrHfbzosvjT_2sPt-Zv8Q51-3ZCcs6Dvqd5eaA

###
GET http://localhost:12346/Users/AAA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvbm5pZUEiLCJpYXQiOjE2ODU3NDE5MDR9.Q6MeczrHfbzosvjT_2sPt-Zv8Q51-3ZCcs6Dvqd5eaA
